/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ca.mcgill.ecse321.projectGroup20;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.test.context.junit4.SpringRunner;

@RunWith(SpringJUnit4ClassRunner.class)
public class projectGroup20ApplicationTest {

    @Test 
    public void contextLoads() throws Exception {

    }

}